### PR TITLE
Consolidation

### PR DESCRIPTION
**Pull request by michael-e**
This PR replaces https://github.com/nathanhornby/hashid_field/pull/33

If everything is ready to be pulled, I will add a commit with the release notes and the 2.0.0 tag.

### CODE REVIEW

**Comment by nitriques** [comment]
@michael-e I'll check this ASAP.

BTW, tags are not push in a PR so I would recommend to not tag it in your repo since it may clash when you fill `git fetch upstream`

**Comment by michael-e** [comment]
Thanks for this info! I didn't know that.

**Comment by nitriques** [comment]
My pleasure ;)

**Comment by michael-e** [comment]
@nathanhornby, what do you think?

**Comment by nitriques** [comment]
@michael-e I'll review and test this tomorrow (I'll try to...)

**Comment by nathanhornby** [comment]
Sorry @michael-e I hadn't dipped in - I'm happy to leave this in you and @nitriques capable hands!

**Comment by michael-e** [comment]
I am happy to let @nitriques try and break this. (But I hope that everything rather bulletproof.)

**Comment by michael-e** [comment]
OK, now we finally have it:

* every update to the field value is done in the compile function(s).
* compiling doesn't require any `entry->commit()`; this is very useful if you add the field to a big existing section or change the field settings — you can update hundreds of thousands of entries (using a script) without committing each entry, by simply calling a delegate!

**Comment by michael-e** [comment]
Thanks!

So next is: Do the same with other extensions, especially the Reflection Field. See https://github.com/symphonists/reflectionfield/issues/27

**Comment by nitriques** [comment]
:D

**Pull request merged**
