### PR TITLE
Update for Symphony 4.x

### PR DESCRIPTION
**Pull request by alexnantel88**
Update release version.
Update styles to fit in with Symphony 4.x layout.

### CODE REVIEW

**Comment by nathanhornby** [comment]
Symphony 4! I'm so out of the loop. @nitriques  if you would be so kind to take a look at this whenever you get a minute I'd be forever grateful.

**Comment by alexnantel88** [comment]
wait for @nitriques to merge it

**Comment by nathanhornby** [comment]
@alexnantel88 Where can I find out more about Symphony 4.x ? I had a quick search but couldn't find anything…

**Comment by nathanhornby** [comment]
Hey @nitriques are you OK to take a look at this one? tbh I'd be happy to transfer ownership of the extension as I work so rarely with Symphony these days - let me know if you wanted to take control.

**Comment by nitriques** [comment]
@nathanhornby It's a shame we've lost you :(  I already have write access so I am good, but if you insist on transfering it, transfer it to DeuxHuitHuit. Thanks!

**Comment by nitriques** [comment]
@alexnantel88 can you please rebase ?!?! Thanks !

**Comment by alexnantel88** [comment]
@nitriques I sure can and I just did.

**Pull request merged**
