### PR TITLE
Version 1.3.0

### PR DESCRIPTION
**Pull request by nitriques**
c4ad03a is the breaking change which justify the minor bump.

I've also made some clean up.

This is here for review: I might merge it if I have not feedback. Thanks!

### CODE REVIEW

**Comment by nathanhornby** [comment]
Thanks @nitriques , appreciated!

Have you found the extension useful in any particular projects, out of interest?

**Comment by nitriques** [comment]
Yes a lot! I use it for auth token and other id that needs to not be guessable !

**Comment by nathanhornby** [comment]
Excellent, really glad it's been useful to someone (even if you have had to do a lot of maintenance :p )

**Comment by nitriques** [comment]
> even if you have had to do a lot of maintenance

I would have had to create it in the first place so I already win ;)

**Comment by nitriques** [comment]
I've just added prepareTextValue implementation (e3ff864) ...

Wanna review ? :P

**Comment by nitriques** [comment]
Released!

**Pull request merged**
