### PR TITLE
Prevent the field from being registered multiple times. Fixes #26

### LINKED ISSUE #26: Field gets registered multiple times
In a [Reflection Field discussion](https://github.com/symphonists/reflectionfield/commit/9045e86f31977d6e9e461d3ef75ef9ec9f3d47c5#commitcomment-10387095) @brendo and me found out that the way the Reflection Field gets registered has big issues. The field may get registered multiple times, which is really bad for performance.

The Hashid Field is using the same logic to register the field (and has the same problems). I will send a pull request shortly.

### PR DESCRIPTION
**Pull request by michael-e**

### CODE REVIEW

**Comment by nathanhornby** [comment]
Thanks for this @michael-e 

I'll look at getting this merged asap. I'll look at bumping versions as well as Symphony has had some updates since the last milestone!

On the to do list.

**Comment by nitriques** [comment]
@nathanhornby We should release 1.2.3 with this... You can give me write access if you want me to do it.

**Comment by nathanhornby** [comment]
Yes, must admit I'd completely forgotten about this @nitriques @michael-e - as you've probably guessed I haven't worked on any Symphony projects for a while, so I'm quite out of the loop (even with my own repos!).

**Comment by nathanhornby** [comment]
I've added you as a collaborator @nitriques - please feel free to merge this request if you can sanity check it.

**Comment by michael-e** [comment]
BTW, I must admit that I also never found the time to care for  https://github.com/nathanhornby/hashid_field/issues/28

Sorry for that, but I am not actively using the extension, so I never had enough pressure to care for this.

**Comment by nathanhornby** [comment]
No probs. @michael-e - you flagged it, that's contribution enough :)

**Comment by nitriques** [comment]
Thanks Nathan!

**Comment by nitriques** [comment]
[Released as 1.2.3](https://github.com/nathanhornby/hashid_field/releases/tag/1.2.3)

**Pull request merged**
